iproute2 tc and bridge integration (#9)
* iproute2-sysrepo: bridge and tc integration
---------
Signed-off-by: Amjad Daraiseh <adaraiseh@okdanetworks.com>

diff --git a/.github/workflows/actions-compile.yml b/.github/workflows/actions-compile.yml
--- a/.github/workflows/actions-compile.yml
+++ b/.github/workflows/actions-compile.yml
@@ -45,7 +45,37 @@ jobs:
         run : CC=${{ matrix.compiler }} make -j $(nproc)
       - name: basic compilation check
         run : ldd bin/iproute2-sysrepo
-      - name: basic test ip address like
-        run : bin/iproute2-sysrepo link
+      - name: basic test "ip link add/set"
+        run : |
+              set -e
+              sudo bin/iproute2-sysrepo ip link add br-slave type dummy
+              sudo bin/iproute2-sysrepo ip link add br0 type bridge vlan_filtering 1
+              if ! sudo bin/iproute2-sysrepo ip link set br-slave master br0; then
+                exit_code=$?
+                if [ "$exit_code" -ne 1 ]; then
+                  echo "Failed: Command failed with unexpected exit code $exit_code"
+                  exit $exit_code
+                fi
+              fi
+      - name: basic test "ip link"
+        run : bin/iproute2-sysrepo ip link
+      - name: basic test "bridge vlan add"
+        run : sudo bin/iproute2-sysrepo bridge vlan add vid 10 dev br-slave
+      - name: basic test "bridge link"
+        run : bin/iproute2-sysrepo bridge link
+      - name: basic test "tc qdisc add"
+        run : sudo bin/iproute2-sysrepo tc qdisc add dev br-slave root netem delay 200ms
+      - name: basic test "tc qdisc"
+        run : bin/iproute2-sysrepo tc qdisc
+      - name: basic test "bad argv0"
+        run : |
+              sudo bin/iproute2-sysrepo bad-arg || exit_code=$?
+              if [ "$exit_code" -eq 1 ]; then
+                  echo "Passed: exited with code 1"
+                  exit 0
+              else
+                  echo "Failed: did not exit with code 1."
+                  exit 1
+              fi
       - name: yanglint
         run : make check
